server.port=8081

#general mode localhost
spring.datasource.url=jdbc:mysql://localhost:3306/experiment
#docker mode host.docker.internal
# spring.datasource.url=jdbc:mysql://host.docker.internal:3306/experiment
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:backend/mapper/*.xml
mybatis.type-aliases-package=backend.entity
mybatis.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.file.name=log/log.log
logging.level.root=info
logging.level.org.mybatis=error
logging.level.java.sql=error
